Repository traefik/mesh-helm-chart, pull requests merged in 2020-09, with the labels that each got.

#1 Fix image name, links and remove testing doc
  README.md
  TESTING.md
  mesh/Chart.yaml
  mesh/README.md
  mesh/values.yaml
Labels: kind/bug/fix, status/3-needs-merge

#2 Add new helm url
  README.md
  mesh/Chart.yaml
  mesh/README.md
Labels: kind/enhancement

#5 Update app version to v1.4.0
  README.md
  mesh/Chart.yaml
  mesh/README.md
Labels: kind/enhancement, status/3-needs-merge
